---

codecov:
  require_ci_to_pass: false

test:
  absolute <relative> (change)
  35% <72%> (+4%)

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false     # [true: must have a base report to post]
  require_head: true      # [true: must have a head report to post]