# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test .NET projects

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - main

    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"

  workflow_dispatch:
    inputs:
      reason:
        description: "The reason for running the workflow"
        required: true
        default: "Manual run"

jobs:
  build:

    permissions:
      checks: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./global.json

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Unit Test
        run: dotnet test --configuration Release --no-restore --no-build --logger trx --results-directory TestResults

      - name: Upload Event File
        uses: actions/upload-artifact@v4
        with:
          name: Event File
          path: ${{ github.event_path }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: TestResults

      - name: Codecov
        uses: codecov/codecov-action@v5.4.3

      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: BlazorApp-test-results
          path: TestResults

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
          versionSpec: "5.x"

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.2.1
      - run: |
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"

        # Use always() to always run this step to
        # publish test results when there are test failures
        if: ${{ always() }}